HTTP_AUTHORIZATION = "HTTP_AUTHORIZATION"
VERIFY_CLIENT_API_KEY = "HTTP_CLIENTAPIKEY"
VERIFY_SERVER_API_KEY = "HTTP_SERVERAPIKEY"
HTTP_APP_VERSION = "HTTP_APPVERSION"
CLIENT_LANG_KEY = "HTTP_ACCEPT_LANGUAGE"

SAFE_METHOD_CLIENT = ['POST']

SAFE_METHOD_MANAGER = ['DELETE', "PUT"]

SAFE_METHOD_EMPLOYEE = ["PUT"]
