# Generated by Django 4.0.5 on 2022-07-02 15:54

from webbrowser import MacOSX
from django.db import migrations, models
from user.choices import EMPLOYEE, CLIENT, MANAGER
from django.contrib.auth.hashers import make_password


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    def create_user(apps, schema_editor):
        User = apps.get_model("user", "User")
        password = make_password("DemoDjango123@")
        User.objects.create(username="employee",
                            password=password, role=EMPLOYEE)
        User.objects.create(username="manager",
                            password=password, role=MANAGER)
        User.objects.create(username="client",
                            password=password, role=CLIENT)

    operations = [
        migrations.CreateModel(
            name='BlacklistToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('iat', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blacklist Token',
                'verbose_name_plural': 'Blacklist Token',
                'db_table': 'd_blacklist_token',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(
                    auto_now_add=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(
                    auto_now=True, verbose_name='Updated Time')),
                ('username', models.CharField(max_length=255,
                 unique=True, verbose_name='User Name')),
                ('password', models.CharField(
                    max_length=255, verbose_name='Password')),
                ('last_login', models.DateTimeField(
                    blank=True, null=True, verbose_name='Last Login')),
                ('role', models.CharField(choices=[('manager', 'Manager'), (
                    'employee', 'Employee'), ('client', 'Client')], default='client', max_length=10)),
            ],
            options={
                'verbose_name': 'User',
                'db_table': 'd_user',
            },
        ),
        migrations.AddIndex(
            model_name='blacklisttoken',
            index=models.Index(
                fields=['user_id', 'iat', 'model'], name='d_blacklist_user_id_6d87a3_idx'),
        ),
        migrations.RunPython(create_user),

    ]
